# Generated by Django 4.1.1 on 2022-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashcode',
            field=models.CharField(blank=True, default='2d5cd88607309a46ddf0', max_length=20, null=True),
        ),
    ]
