# Generated by Django 4.1.1 on 2022-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_user_hashcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
