# Generated by Django 4.1.1 on 2022-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_user_hashcode_alter_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userhub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashid', models.CharField(default='', max_length=20)),
                ('users', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
