# Generated by Django 4.1.1 on 2022-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_userhub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashcode',
            field=models.CharField(blank=True, default='da39a3ee5e6b4b0d3255', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
