# Generated by Django 4.1.1 on 2022-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_alter_user_hashcode_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashroom', models.CharField(default='', max_length=200)),
                ('sender', models.CharField(default='', max_length=200)),
                ('receiver', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
