# Generated by Django 4.1.1 on 2022-12-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='username@gmail.com', max_length=50, unique=True),
        ),
    ]
