# Generated by Django 4.1.1 on 2022-12-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=20)),
                ('sender', models.CharField(default='', max_length=30)),
                ('receiver', models.CharField(default='', max_length=30)),
                ('message', models.TextField(default='')),
                ('messageid', models.IntegerField(default=0)),
                ('fileAttached', models.BooleanField(default=True)),
                ('filelink', models.TextField(default='')),
            ],
        ),
    ]
